### ISSUE TITLE
Coordinates detection wile iPhone not moving

### ISSUE THREAD

**Issue by ghost** [dsdavids/TTLocationHandler#1]
Hi, i am 1110 from stack you helped me with getting location background.
I use your classes and it work's fine but have one issue.
When I don't move iPhone (in the room) it still getting some random coordinates around me accross the street 5m from me, 20m from me 50m from me.
This is images with coordinates that I get while not moving iPhone:

http://s11.postimage.org/aon3e8kxf/IMG447.jpg
http://s11.postimage.org/ivf35tb03/IMG448.jpg
http://s11.postimage.org/530oa6k8j/IMG449.jpg

**Comment by dsdavids** [comment]
What have you set for requiredAccuracy? If you have it set at 10m and are processing locations as far as 50m off, I assume you are not having enough signal strength and so the handler is defaulting to accepting best available. 
You can tweak this behavior, allowing more time and/or more tries by changing MAX_TRIES_FOR_ACCURACY const and _pendingLocationsTimer iVar values to higher numbers. The defaults I have set are 10 tries and 10 seconds. This means, if location is not within the required accuracy, it will hold for 10 seconds waiting to see if another is received. It will do this 10 times before giving up and accepting what it has as the best available.
You can play around with different settings and observe the logs to confirm. I would start by lowering the requiredAccuracy property. Watch the console and confirm if it is reaching maxTime or maxTries, then you may narrow down what is best to adjust from there.
Other options are that you may want to test the accuracy again prior to saving it or disable the acceptBestAvailable method completely, let it keep trying indefinitely for a better fix.

What device are you using? I have noticed that 3GS is horribly inaccurate, 4 is better, 4S is very good and 5 better still. These are the only devices I have tried.

If you really wanted to get carried away you could go another route, saving several locations in array, make a region out of them and consider your actual location as the center of that region. I can envision this as a method to average out all the various results and smooth the data for plotting as you appear to be doing.

I think what I would do, after trying some combinations of accuracy and max tries, is to check the accuracy and the distance moved prior to saving and plotting. If it is not within your required accuracy, is it far enough from previous to be considered? Then you can decide to save, ignore or go to further confirmation processes.

Dean S. Davids

**Comment by dsdavids** [comment]
If you want to, start a fork and add your logging class to it. I will take a look and perhaps see a better way.

**Comment by ghost** [comment]
I have tried to change MAX_TRIES_FOR_ACCURANCY and requiredAccurancy and what ever I put small or large number it always move in a closed room.
I downloaded 'LocateMe' and run it and it adds pins to map when I am not moving.
You have right. Signal is weak.
I am using iPhone 4.

**Comment by dsdavids** [comment]
I added a couple of things to eliminate your issue and it seems to have succeeded in my own tests. There is now a property to set, ignorePossibleDuplicates. The default setting is YES. I moved the distance filter setting to a constant which can be tweaked as well, depending on your own purpose.

The distanceFilter property of CLLocationManager has actually just been deprecated as of iOS6. I can't imagine why as they do not seem to have given an alternative to use in its place. I guess the activityType property is meant to take over that function in some abstract fashion but it means they are taking away some of the finer control we once had. The changes I made here will bring that decision making back into our handler even after distanceFilter is no longer supported.

**Comment by dsdavids** [comment]
I added some elements to the demo to allow messing with the configuration and see the result. I tested for your issue on my own device and found favorable results. Try it out now, if you no longer get the extraneous duplicates I will close this issue.

**Comment by ghost** [comment]
Now it doesn't move at all. I start walking but just first coordinate was saved. It doesn't add new coordinates.

**Comment by dsdavids** [comment]
Walking? That would require some changes for more sensitivity. I'll play with the settings and make a walking mode.

**Comment by dsdavids** [comment]
At the default setting I had set, you would have to walk at least 50m plus the adjustments for accuracy of reading, effectively a minimum of 70m, possibly further. I am thinking that is workable for automobile tracking. I made another toggle button and tested some alternate settings for walking. This is going to be a balancing act between sensitivity high enough for your purpose, while still filtering out the random off track reports.

Try it now. In walk mode, it will accept reports on movement of 10-30 meters. You can try other settings to get what you need. In TTLocationHandler.m change the value of WALK_DISTANCE_FILTER. I have it at 10m but accuracy rarely goes below 10m so our ignorePossibleDuplicates setting will increase it as applicable. Expect around 30 meters the likely trigger point in most cases.

If you set that below 10m, it will report more frequently, but I am sure you will start getting more unwanted reports when stationary as well.

**Comment by ghost** [comment]
Sorry I didn't know that it was not set for walking. I will drive tomorrow to test it :) And I need it for driving I just didn't test in car today :(

**Comment by dsdavids** [comment]
With walkMode enabled, it seems well balanced. I have been trying it out some and get the results I expected.

**Comment by ghost** [comment]
Tested it today. After driving I get again in office and after a few minutes I get some wired coordinate but it's not important it happens just once. It's far better :) thanks. I noticed one more thing, application doesn't work if I turn off internet. I thought that GPS doesn't require internet connection or I am wrong?

**Comment by dsdavids** [comment]
Part of the hocus pocus behind Apple's "Location Services" relies heavily on wifi and cell signals for sure. I know it doesn't work in airplane mode. If you turned off wifi and cellular individually, I know significantLocationMonitoring and regionMonitoring won't work. I would expect continuous updating would still work though.

**Comment by ghost** [comment]
And I found one more thing I will try to change code tomorrow (if this is not apple bug :) ) if user kills app location service continue to work and drain battery. It has something with "startMonitoringSignificantLocationChanges" http://stackoverflow.com/questions/4872055/locationservice-indicator-stays-on

**Comment by dsdavids** [comment]
I don't think that is a bug, or even an issue. If the app has called startMonitoringForsignificantLocationChanges, it can be killed or deleted or whatever you like. It is not using or causing any other power to be used. It is normal for the location services indicator to show in status bar if there is an app that has called that mode. When the system decides that a significant change in location has happened, it will attempt to call up the app which will or will not respond. If the app no longer exists on the device nothing happens. If there are no other apps using the services, the indicator goes away.
significant location monitoring relies completely on cell and wifi signals which, conceivably, are operating normally regardless of the location services status. This is why it works so well to minimize battery waste.

Dean
