### ISSUE TITLE
startMonitoringSignificantLocationChanges clarification

### ISSUE THREAD

**Issue by CeccoCQ** [dsdavids/TTLocationHandler#2]
Hi,

great app!
I've a doubt, using your app to understand the location tracking mechanism of ios.
When I set background update to OFF, the app works only with startMonitoringSignificantLocationChanges, but if I simulate the location changes with simulator (into debug section) the didUpdateToLocation is never called.

So, I'm wondering how I can handle the location changes. My simulation changes the position from Hong Kong to London.

Where is my mistake?

**Comment by dsdavids** [comment]
It has been a while since I was working these things out but one thing I do remember is that the simulator was of limited use for debugging. Very inconsistent. I set up my macbook in my truck and drove around logging events when I really wanted to test my processes.

Dean

**Comment by CeccoCQ** [comment]
Thanks for your response.
Tomorrow I'll try within my car ;)

One doubt: if I use startMonitoringSignificantLocationChanges when my app comes in background, teorically I might remove UIBackgroundModes from plist file? In your code, how you manage this?

**Comment by dsdavids** [comment]
In fact, Apple would not approve my app without that I took out the background mode. If you can do without, they will not allow it. 

Dean S. Davids
www.cmbscorp.com
954-868-4421

**Comment by CeccoCQ** [comment]
So, at the end, the startMonitoringSignificantLocationChanges (without UIBackgroundModes enabled) can awake my app in background state within didUpdateToLocation delegate method. Within this method, I can perform UIBackgroundTask operation (life method = 10 minutes), for example, send the new location to server.
I need  UIBackgroundModes enabled only when I use startUpdatingLocation in background, 

Is it ok?

**Comment by dsdavids** [comment]
That is the way I remember it. There is a delegate method in app delegate that can tell your app that it was launched by a location event. I experimented with altering the launch routines there but found no real benefit. UI elements are ignored when the app is in the background anyway.
Problems I remember most with background operations were with timers and runloops. If all you need to do is send current location to a server, I assume you will let your method respond to didUpdatetoLocation same as if it was in the foreground.

Dean

**Comment by CeccoCQ** [comment]
Perfect, I've undestarnd you completely.

Last question: from your testing and your experience, if I use startUpdatingLocation for background tracking (with UIBackgroundMode enabled) with this configuration:

self.bgLocationManager.desiredAccuracy = kCLLocationAccuracyKilometer;
self.bgLocationManager.distanceFilter = 250.0;
[self.bgLocationManager startUpdatingLocation];

there will be a high consumption of battery?

**Comment by dsdavids** [comment]
Any use of the location manager continuous, in background or not, is sure to affect battery life. I think that increasing the distance filter helps to limit your app processing in response to events but does not alleviate the need for the manager to continuously survey the signals to see if the filter setting is met. SignificantLocationChanges takes the hardware out completely, bringing it back up when a large change is detected. You will certainly better serve your users if you can manage to get what you need from the latter method. Moreover, based on my experience with submittal, your app will not be likely be approved with background mode if it is not absolutely essential to your objective and your objective is within their terms of use.

In my case, I could easily demonstrate that my app was having no effect on battery life at all, as background mode was only used if the device was plugged into power. It was not approved and my appeal rejected out of hand.

Note, if you use accuracyKilometer I think you will have very inconsistent results trying to determine movement of 250 meters.

Perhaps you could use region monitoring instead. Set a region with 250 radius, process on departure and reset to new region. Seems that would work just as well. If the user is stationary, app will sleep appropriately, otherwise wake up on 250m travel.

Dean

**Comment by CeccoCQ** [comment]
Dean, thanks for all!!!!!

In the end I chose to use the SignificantLocationChanges method when app comes into background mode, and test its behaviour with my car. I walked about 13 km with my car in 20 minutes using your LocateMe app with SignificantLocationChanges method (into background). But after 20 minutes, when I re-opened the application, I see only a pin at the position when my app comes into background mode at first time. So, I'm wondering when your event (handleLocationUpdate) was called from significant location change.

Also, if I remove the UIBackgroundModes string from plist file, the SignificantLocationChanges can awake the app after 10 minutes (calling didUpdateToLocation). Is it right?

**Comment by dsdavids** [comment]
Your reaching the bounds of my memory now. I would have to review my own code to answer some of that. LocateMe was quick and simple mashup, but as I remember it did work. 

The process, when waking is as follows:
-app wakes, launches in background
-handler, listening for appDidFinishLaunching, sends message to startMonitoringLocation 
-now you will start receiving updates and respond in didUpdateToLocation
-once you have tested and accepted a location as within your accuracy and recency parameters, you process the event and then go back to monitoring for significant location changes or regions or both as applicable.

This all works the same with or without the background mode setting. Without that flag, your app will likely be suspended within 10 minutes or less so the idea is to do what you need to do ASAP then stand ready for next notification. 

Dean

**Comment by kirank-canwill** [comment]
Hi Dean,

Thanks so much for Developed Good App !!!

With the reference of  provided sample code and I developed one application. In addition I have
added background location permission, which required for new iOS 8. 

In my application I want location update continually when application have in background mode, Inactive , suspended and even if app in kill mode. (Battery drain is not problem)

As per my understanding I notice that  [[self locationManager] stopUpdatingLocation]; method stop when application not in “ActiveMode” and Start another  [self.locationManager startMonitoringSignificantLocationChanges]; 

In my application I written log file for tracking device location. I am facing some problem on below scenario. 

I’m traveling 1 hr, and my application have in Kill mode. that time I did’t find updated location in my log file. Does need more setting for use [self.locationManager startMonitoringSignificantLocationChanges]. 

Could you please suggest the solution?

Thanks

**Comment by dsdavids** [comment]
I haven’t fiddled with this code in a very long time so memory not so good. It is in my own delivered app pretty much as is and has never had an issue to go back to.

That being said, I remember the class has a switch for background updates. In my app I was switching it to true only when the device was plugged in to power. I thought this was reasonable use and conservative battery management. Apple did not agree, they rejected my app and I had to remove that code.

If your app meets the guidelines for use in background, you should have no trouble enabling the background mode. There is a key you need in the inf.plist, I don’t remember exactly but search should confirm.

If your app is killed, by a crash or by the system for other reasons, while in background then it should still be awakened on significant location update or region entry/exit event. Make sure you are rebuilding and restarting the TTLocationHandler class when awakened in that way and you should be golden.

Dean S. Davids
Fort Lauderdale, FL USA

**Comment by kirank-canwill** [comment]
thanks for quick reply..
I have added NSLocationAlwaysUsageDescription and  NSLocationWhenInUseUsageDescription in info.plist. 

Will check as you suggested..
Thanks so much..

**Comment by mythodeia** [comment]
@kirank-canwill did you have any success with background updates and significantlocation updates?
i do not get any updates when the app is killed

**Comment by kirank-canwill** [comment]
@mythodeia, Yes I got success.IOS9 also added extra key to get location update while  your app have in background OR suspended /Kill mode.  see below line.
if(SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"9.0")){
         [self.locationManager setAllowsBackgroundLocationUpdates:YES];
   }.

NOTE: Significant location  location method call 10-15 min. Once your device location channel changed that time Significant location method call.

**Comment by mythodeia** [comment]
@kirank-canwill thanks for answering.
i have that line already. I will drive around for half an hour then so i can do some proper tests because standing in front of the mac is not doing any good :)

**Comment by kirank-canwill** [comment]
@mythodeia ,While you drive that time location not update. When you stop somewhere that time location method call.

**Comment by mythodeia** [comment]
@kirank-canwill did you find any way to get updates even while driving?

**Comment by kirank-canwill** [comment]
I never tried..Might be we can.

**Comment by zeeshansuleman** [comment]
@kirank-canwill @dsdavids  i am using significantlocationchange in my app , but i am unable to get any location update.consider the scenario.
1:I put my app in background with significantlocationchange.
2:I drived about 10 km but in the app no event is triggered.
3:I have also added code in appdidfinishlaunching,as i heared that when app wake up with location event this method get called with a "UIApplicationLaunchOptionsLocationKey".But it also not called.given is my code to debug when app become active with location event.

if (launchOptions[UIApplicationLaunchOptionsLocationKey]) {
        UILocalNotification *localNotification = [[UILocalNotification alloc] init];
        localNotification.fireDate = [NSDate dateWithTimeIntervalSinceNow:2];
        localNotification.alertBody = @"app wakeup with a location update.";
        localNotification.soundName = UILocalNotificationDefaultSoundName;
        [[UIApplication sharedApplication] scheduleLocalNotification:localNotification];
    }

**Comment by murali9** [comment]
@kirank-canwill how to get continuous location details when app is killed/Terminated. startMonitoringSignificantLocationChanges method firing the didUpdateLocations after 500 meters. But i want location updates in kill mode for every 10 meters.
