### ISSUE TITLE
How to stop TTLocationHandler

### ISSUE THREAD

**Issue by ghost** [dsdavids/TTLocationHandler#3]
I want to be able to start/stop TTLocationHandler. 
I have moved it's logic from AppDelegate to the button handler and it start normally when I want but when I try to stop it application crash.
To stop I used:
[self.sharedLocationHandler.locationManager stopUpdatingLocation];

Is it possible to easy stop tracking?

PS
And I made a little improvement to the app (I asked you in mail but I made it my self) instead of pins it draw a MKPolygon path. I will upload it somewhere when I make sure everything works fine.

**Comment by dsdavids** [comment]
stopUpdatingLocation is a valid message for CLLocationManager so I presume that is not the issue. What else are you doing in the method? What do you see in logs?

Dean

**Comment by ghost** [comment]
This is whole code from button:
LMAppDelegate *appDelegate = (LMAppDelegate *)[[UIApplication sharedApplication] delegate];

```
if(appDelegate.isTrackingOn == NO)
{
[self.btn_StartTracking setTitle:@"Stop" forState:UIControlStateNormal];
// Set up the PinTracker
self.pinTracker = [[LMPinTracker alloc]init];
self.pinTracker.uploadInterval = 60.0;

// Set up the location handler.
self.sharedLocationHandler = [TTLocationHandler sharedLocationHandler];
self.sharedLocationHandler.locationManagerPurposeString =
NSLocalizedString(@"LOCATION SERVICES ARE REQUIRED FOR THE PURPOSES OF THE APPLICATION TESTING", @"Location services request purpose string.");

// Set background status. Update continuosly in background only when plugged in or regardless of power state.
self.sharedLocationHandler.updatesInBackgroundWhenCharging = YES;
// UPDATING IN BACKGROUND WHILE ON BATTERY WILL IMPACT THE USER'S BATTERY LIFE CONSIDERABLY
self.sharedLocationHandler.continuesUpdatingOnBattery = YES;

// Set interval of notices on change of location
self.sharedLocationHandler.recencyThreshold = 10.0;
}
else
{
    [self.btn_StartTracking setTitle:@"Start" forState:UIControlStateNormal];

    [self.sharedLocationHandler.locationManager stopUpdatingLocation];
}
```

When app crach it puts break point here:
int main(int argc, char *argv[])
{
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([LMAppDelegate class]));
    }
}

This is the log:
2013-06-28 15:40:40.114 LocateMe[13992:c07] Sending notification out
2013-06-28 15:40:40.114 LocateMe[13992:c07] -[__NSCFNumber handleLocationUpdate]: unrecognized selector sent to instance 0x8463790
2013-06-28 15:40:40.212 LocateMe[13992:c07] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber handleLocationUpdate]: unrecognized selector sent to instance 0x8463790'
**\* First throw call stack:
(0x18c0012 0x1280e7e 0x194b4bd 0x18afbbc 0x18af94e 0xd414f9 0x191a0c5 0x1874efa 0xc88a0c 0x9796 0x2e1753f 0x2e29014 0x2e197d5 0x1866af5 0x1865f44 0x1865e1b 0x1cff7e3 0x1cff668 0x1c4ffc 0x1d7d 0x1ca5)
libc++abi.dylib: terminate called throwing an exception

**Comment by ghost** [comment]
It was my error nothing with project sorry.

**Comment by ghost** [comment]
Sorry for reopening this but I didn't want to open new. But again I have issues with stoping GPS scanning when add it to my project.
I use this code for stop:
       [self.sharedLocationHandler.locationManager stopUpdatingLocation];
        self.sharedLocationHandler.updatesInBackgroundWhenCharging = NO;
        self.sharedLocationHandler.continuesUpdatingOnBattery = NO;
        self.sharedLocationHandler = nil;
But after this all goes wired (probably I did something wrong):
- GPS Icon on status bar never disappear even after I close the app. When I delete app then it disappear (TTLocationHandler is Singleton pattern as I understand maybe this make some issue).
  It's obvious that my stop code doesn't work.
- What am I doing wrong? I want to STOP tracking completely for example to START new tracking again.

**Comment by AymanElarian** [comment]
any new how to stop it ?

**Comment by dsdavids** [comment]
Ayman,
Simply calling stopUpdatingLocation should be all that is necessary to stop location services. Vlad issues were not related to that.

**Comment by AymanElarian** [comment]
thanks for your replay
if i will call it like that  it will work with delay 
    [[NSNotificationCenter defaultCenter] addObserver:self.sharedLocationHandler selector:@selector(_stopUpdatingLocation) name:UIApplicationDidEnterBackgroundNotification object:nil];

how to call _stopUpdatingLocation direct ?

**Comment by AymanElarian** [comment]
also if i put it inside triger button it not work

**Comment by dsdavids** [comment]
There are various settings that may allow location services to continue, _stopUpdatingLocation is not meant to be a direct switch.
[[[TTLocationHandler sharedLocationHandler] locationManager] stopUpdatingLocation] would be a direct call to the location manager and would stop location services regardless of any settings

**Comment by AymanElarian** [comment]
thanks
