### ISSUE TITLE
Simulator - current location (blue) pin on map stop moving after few seconds

### ISSUE THREAD

**Issue by ghost** [dsdavids/TTLocationHandler#8]
I didn't test this on real device but on simulator blue pin moves a two-three times and stop but LMAnnotation continue to add on current location. It's just current pin not moving.

**Comment by ghost** [comment]
![screen shot 2014-02-19 at 11 14 34 am](https://f.cloud.github.com/assets/361205/2205917/09f84640-9958-11e3-8d9b-da8265384b28.png)

**Comment by dsdavids** [comment]
Have you set the simulator to one driving or walking?

Dean Davids
www.deansdavids.com

**Comment by ghost** [comment]
driving, annotation drop fine but blue pin stop and not moving, on second location.

**Comment by ghost** [comment]
I will close this issue as this is probably something with mine simulator because I have used TTLocationHandler in anther app and it works fine.

**Comment by dsdavids** [comment]
I see the same in my simulator. Have never noticed it before. All appears working properly otherwise. I have no idea why the user location indicator is not moving.

**Comment by ghost** [comment]
I have used TTLocationHandler in another app (https://github.com/1110/common-location-features) and it works fine :). It's something stupid for sure :)
